[build-system]
# Minimum requirements for the build system to execute.
requires = ["setuptools", "wheel"]  # PEP 508 specifications.

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
#pythonpath = "tests/"

pythonpath = [
  "src"
]